// FissionQuest V4 Arcade
// Depends on helpers from script.js

// 1) NEUTRON DASH
const dc=$("#dashCanvas"), dctx=dc?.getContext("2d");
let dash={run:false,x:460,score:0,items:[],keys:{},last:0};
function drawBg(){if(!dctx)return;let g=dctx.createLinearGradient(0,0,0,dc.height);g.addColorStop(0,"#071923");g.addColorStop(1,"#040a0e");dctx.fillStyle=g;dctx.fillRect(0,0,dc.width,dc.height);dctx.strokeStyle="rgba(88,228,255,.06)";for(let x=0;x<dc.width;x+=50){dctx.beginPath();dctx.moveTo(x,0);dctx.lineTo(x,dc.height);dctx.stroke()}}
function drawItem(it){dctx.fillStyle=it.type==="u"?"#cf5858":"#66757e";dctx.beginPath();dctx.arc(it.x,it.y,it.type==="u"?22:19,0,Math.PI*2);dctx.fill();dctx.fillStyle="#fff";dctx.font="bold 11px sans-serif";dctx.textAlign="center";dctx.fillText(it.type==="u"?"U-235":"ABS",it.x,it.y+4)}
function dashLoop(t){if(!dc)return;drawBg();if(dash.run){if(dash.keys.ArrowLeft||dash.keys.a)dash.x-=6;if(dash.keys.ArrowRight||dash.keys.d)dash.x+=6;dash.x=Math.max(20,Math.min(dc.width-20,dash.x));if(t-dash.last>620){dash.last=t;dash.items.push({x:35+Math.random()*(dc.width-70),y:-25,type:Math.random()<.74?"u":"a",v:3+Math.random()*1.6})}dash.items.forEach(o=>o.y+=o.v);dash.items=dash.items.filter(o=>{if(Math.hypot(o.x-dash.x,o.y-(dc.height-38))<38){if(o.type==="u"){dash.score++;$("#dashScore").textContent=dash.score;if(dash.score>=10){dash.run=false;showMeme("😎","Neutron speedrunner","10 U-235 targets collected. Absorber blocks are filing a complaint.",160)}}else{dash.score=Math.max(0,dash.score-1);$("#dashScore").textContent=dash.score;toast("Neutron absorbed! -1 point")}return false}return o.y<dc.height+25})}dash.items.forEach(drawItem);dctx.fillStyle="#58e4ff";dctx.beginPath();dctx.arc(dash.x,dc.height-38,16,0,Math.PI*2);dctx.fill();dctx.fillStyle="#041016";dctx.fillText("n",dash.x,dc.height-34);requestAnimationFrame(dashLoop)}
if(dc){requestAnimationFrame(dashLoop);$("#dashStart").onclick=()=>{dash={...dash,run:true,x:dc.width/2,score:0,items:[],last:0};$("#dashScore").textContent=0};addEventListener("keydown",e=>dash.keys[e.key]=true);addEventListener("keyup",e=>dash.keys[e.key]=false);$("#dashLeft").onpointerdown=()=>dash.keys.ArrowLeft=true;$("#dashLeft").onpointerup=()=>dash.keys.ArrowLeft=false;$("#dashRight").onpointerdown=()=>dash.keys.ArrowRight=true;$("#dashRight").onpointerup=()=>dash.keys.ArrowRight=false}

// 2) FUSION FORGE
let fusionRun=false,fusionEvents=0,fusionTimer;
function updateFusionVisual(){const t=+$("#tempSlider").value,c=+$("#confSlider").value;$("#tempVal").textContent=t;$("#confVal").textContent=c;const size=90+t*.7;$("#plasmaBall").style.width=size+"px";$("#plasmaBall").style.height=size+"px";$("#plasmaBall").style.filter=`brightness(${.8+t/100})`;if(fusionRun){let state="Plasma warming...";if(t<60)state="Too cold: nuclei rarely overcome repulsion.";else if(c<55)state="Confinement too weak: plasma is escaping.";else if(t>92&&c<70)state="Very hot but unstable — strengthen confinement.";else if(t>=70&&c>=65){state="Fusion conditions achieved!";if(Math.random()<.18){fusionEvents++;$("#fusionScore").textContent=fusionEvents;$("#fusionFlash").style.opacity=1;setTimeout(()=>$("#fusionFlash").style.opacity=0,180);if(fusionEvents>=8){clearInterval(fusionTimer);fusionRun=false;showMeme("☀️","Tiny star energy","You balanced temperature and confinement long enough for repeated fusion events.",180)}}}$("#fusionState").textContent=state}}
$("#tempSlider")?.addEventListener("input",updateFusionVisual);$("#confSlider")?.addEventListener("input",updateFusionVisual);$("#fusionStart")?.addEventListener("click",()=>{if(fusionRun)return;fusionRun=true;fusionEvents=0;$("#fusionScore").textContent=0;fusionTimer=setInterval(updateFusionVisual,350);setTimeout(()=>{if(fusionRun){clearInterval(fusionTimer);fusionRun=false;if(fusionEvents<8)showMeme("🫠","Plasma said 'bye'","You made some progress, but fusion wants both high temperature and strong confinement.",70)}},18000)});updateFusionVisual();

// 3) SORTING LAB
const cards=[
["U-235","⚛","fission"],["D + T","☀️","fusion"],["Control rods","🛑","reactor"],["Containment","🏢","safety"],["Moderator","💧","reactor"],["Criticality","💥","fission"],["Plasma","🔥","fusion"],["Decay heat","♨️","safety"],["Fission fragments","💥","fission"],["Magnetic confinement","🧲","fusion"],["Coolant","🌊","reactor"],["Defence in depth","🛡️","safety"]
];
let order=[...cards].sort(()=>Math.random()-.5),si=0,sortScore=0;
function loadSort(){if(si>=order.length){showMeme(sortScore>=10?"🏆":"🧪",sortScore>=10?"Classification master":"Lab complete",`You scored ${sortScore}/12 in Nuclear Sorting Lab.`,sortScore>=10?150:70);si=0;sortScore=0;order=[...cards].sort(()=>Math.random()-.5);$("#sortScore").textContent=0}const c=order[si];$("#sortTerm").textContent=c[0];$("#sortIcon").textContent=c[1];$("#sortHint").textContent="Choose the best category."}
$$("[data-zone]").forEach(b=>b.onclick=()=>{const c=order[si];if(b.dataset.zone===c[2]){sortScore++;$("#sortScore").textContent=sortScore;toast("Correct ✓");addXP(10)}else toast(`Not quite — ${c[0]} belongs to ${c[2]}.`);si++;loadSort()});if($("#sortTerm"))loadSort();

// 4) QUIZ BOSS
const quiz=[
["Which statement best describes nuclear fission?",["A heavy nucleus splits into smaller nuclei","Two light nuclei join","Electrons leave an atom","Water becomes steam"],0,"Fission is a nuclear process in which a heavy nucleus splits."],
["Why are neutrons useful for inducing U-235 fission?",["They are positively charged","They have no electric charge","They are electrons","They are made of light"],1,"Neutral neutrons are not repelled by positive nuclear charge."],
["What does k ≈ 1 mean in a reactor?",["The chain reaction is steady","The reactor is exploding","No neutrons exist","Fusion has started"],0,"At k≈1 the neutron population is maintained from generation to generation."],
["What is the main job of control rods?",["Absorb neutrons","Produce uranium","Spin the turbine","Create steam directly"],0,"Control rods change reactivity by absorbing neutrons."],
["Why is a moderator used in many thermal reactors?",["To slow neutrons","To speed up neutrons","To store waste","To make electricity"],0,"Thermalised neutrons are effective for U-235 fission."],
["Why must a shut-down reactor still be cooled?",["Decay heat continues","Gravity creates fission","Electrons melt the core","The turbine heats the fuel"],0,"Radioactive fission products continue releasing decay heat after shutdown."],
["Which is true for a BWR?",["Water boils in the reactor vessel","The primary loop never boils","It uses fusion","It has no coolant"],0,"A BWR generates steam directly in the reactor vessel."],
["What important feedback contributed to the Chernobyl power excursion?",["Positive void-reactivity feedback","Solar feedback","Magnetic confinement","Negative mass defect"],0,"Under the accident conditions, more steam voids could increase reactivity."],
["What is nuclear fusion?",["Joining light nuclei","Splitting U-235","Absorbing gamma rays","Burning uranium chemically"],0,"Fusion combines light nuclei and powers stars."],
["Why can fission release energy?",["Products can be more tightly bound, leaving lower total mass-energy","Protons vanish","Water creates energy","Neutrons have infinite energy"],0,"Binding-energy differences correspond to a mass-energy difference released as kinetic energy and radiation."]
];
let qi=0,qscore=0;
function loadBoss(){const q=quiz[qi];$("#bossNo").textContent=qi+1;$("#bossQuestion").textContent=q[0];$("#bossChoices").innerHTML="";q[1].forEach((x,i)=>{const b=document.createElement("button");b.textContent=x;b.onclick=()=>answerBoss(i,b);$("#bossChoices").appendChild(b)});$("#bossExplain").textContent=""}
function resultMeme(s){if(s===10)return["🥹","I'm so proud of you!","10/10. The reactor is stable, the examiner is impressed, and the nucleus respectfully salutes you.",300];if(s>=8)return["😎","Nuclear scholar detected",`${s}/10. Very strong. You may enter the control room... academically.`,220];if(s>=6)return["👍","Solid result",`${s}/10. Good understanding — review the accident physics and criticality details for the next level.`,150];if(s>=4)return["😅","We can work with this",`${s}/10. Not a disaster, but U-235 is asking you to reread Modules 2 and 3.`,90];if(s>=2)return["💀","Result so bad the control rods inserted themselves",`${s}/10. The good news: your second attempt has enormous growth potential.`,50];return["😭","Bro studied the wrong nucleus",`${s}/10. Please return to the study modules before the neutron files a complaint.`,30]}
function answerBoss(i,b){const q=quiz[qi];$$("#bossChoices button").forEach(x=>x.disabled=true);if(i===q[2]){qscore++;b.style.borderColor="var(--green)";$("#bossExplain").textContent="✓ "+q[4];addXP(20)}else{b.style.borderColor="var(--red)";$("#bossExplain").textContent="✕ "+q[4]}setTimeout(()=>{qi++;if(qi<quiz.length)loadBoss();else{const m=resultMeme(qscore);showMeme(...m);qi=0;qscore=0;loadBoss()}},1250)}
if($("#bossQuestion"))loadBoss();

// 5) QUICK REACTIONS
$$(".reaction").forEach(b=>b.onclick=()=>{localStorage.setItem("fqFeedbackReaction",b.dataset.reaction);$("#reactionSummary").textContent=`Thanks! Your quick reaction ${b.dataset.reaction} is saved on this device. Add a public comment below if you want others to see it.`;toast("Feedback saved")});
